::: {.panel-tabset}

## Intercept-Only 

### Stan

```{r}
#| warning: false

fstan_intercept <- load_or_fit_stan(data, "stan_intercept", cstan_intercept)
fstan_intercept_summary <- fstan_intercept$summary(variables = c("mu", "sigma"))
fstan_intercept_time <- fstan_intercept$time()
```

```{r}
#| echo: false
#| warning: false

kable(fstan_intercept_summary)
kable(fstan_intercept_time$chains)
```

### brms

```{r}
#| warning: false

brms_intercept <- load_or_fit_brms(
  model_name = "brms_intercept",
  data = data,
  formula = phen ~ 1,
  family = gaussian(),
  data2 = list(A = A),
  prior = c(
    prior(normal(0, 50), "Intercept"),
    prior(student_t(3, 0, 20), "sigma")
  )
)
summary(brms_intercept)
```

## Linear Regression

### Stan

```{r}
#| warning: false

fstan_linear <- load_or_fit_stan(data, "stan_linear", cstan_linear)
fstan_linear_summary <- fstan_linear$summary(variables = c("mu", "beta_b", "beta_w", "sigma"))
fstan_linear_time <- fstan_linear$time()
```

```{r}
#| echo: false
#| warning: false

kable(fstan_linear_summary)
kable(fstan_linear_time$chains)
```

### brms

```{r}
#| warning: false

brms_linear <- load_or_fit_brms(
  model_name = "brms_linear",
  data = data,
  formula = phen ~ spec_mean_cf + within_spec_cf,
  family = gaussian(),
  data2 = list(A = A),
  prior = c(
    prior(normal(0, 50), "Intercept"),
    prior(normal(0, 10), "b", coef = "spec_mean_cf"),
    prior(normal(0, 10), "b", coef = "within_spec_cf"),
    prior(student_t(3, 0, 20), "sigma")
  )
)
summary(brms_linear)
```

## MultiPhylo

### Stan

```{r}
#| warning: false

fstan_multiphylo <- load_or_fit_stan(data, "stan_multiphylo", cstan_multiphylo)
fstan_multiphylo_summary <- fstan_multiphylo$summary(variables = c("mu", "beta_b", "beta_w", "sigma_phy", "sigma_sp", "sigma"))
fstan_multiphylo_time <- fstan_multiphylo$time()
```

```{r}
#| echo: false
#| warning: false

kable(fstan_multiphylo_summary)
kable(fstan_multiphylo_time$chains)
```

### brms

```{r}
#| warning: false

brms_multiphylo <- load_or_fit_brms(
  model_name = "brms_multiphylo",
  data = data,
  formula = phen ~ spec_mean_cf + within_spec_cf + (1|gr(phylo, cov = A)) + (1|species),
  family = gaussian(),
  data2 = list(A = A),
  prior = c(
    prior(normal(0, 50), "Intercept"),
    prior(normal(0, 10), "b", coef = "spec_mean_cf"),
    prior(normal(0, 10), "b", coef = "within_spec_cf"),
    prior(student_t(3, 0, 20), "sd", group = "phylo"),
    prior(student_t(3, 0, 20), "sd", group = "species"),
    prior(student_t(3, 0, 20), "sigma")
  )
)
summary(brms_multiphylo)
```

## BYM2Params

### Stan

```{r}
#| warning: false

fstan_bym2 <- load_or_fit_stan(data, "stan_bym2", cstan_bym2)
fstan_bym2_summary <- fstan_bym2$summary(variables = c("mu", "beta_b", "beta_w", "sigma_t", "rho", "sigma", "sigma_phy", "sigma_sp"))
fstan_bym2_time <- fstan_bym2$time()
```

```{r}
#| echo: false
#| warning: false

kable(fstan_bym2_summary)
kable(fstan_bym2_time$chains)
```

### brms

```{r}
#| warning: false

# No BRMS Model
```

:::